version: '3.0'

services:
  php-fpm:
    build: .dockerfiles/php
    restart: always
    container_name: php-sanya
    volumes:
      - .:/app
    working_dir: /app

  web:
    image: nginx
    container_name: web-sanya
    volumes:
      - ./.dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - 8089:80
    restart: always
    depends_on:
      - php-fpm

  composer:
    image: composer
    container_name: composer-sanya
    volumes:
      - ./:/app
    command: composer install